### ISSUE TITLE
预测时出错

### ISSUE THREAD

**Issue by Veyronl** [whgaara/pytorch-soft-masked-bert#15]
大佬,你好,预测的时候出错,即用step3时,出现错误(用的给的样例文本)
![image](https://user-images.githubusercontent.com/46363468/122359951-99563e00-cf88-11eb-8b65-78f2dffe18fd.png)

**Comment by whgaara** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，感谢你的发现，我之前调整模型时忘记修改inference部分，现在已经更新代码，你pull一下即可。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                695509060
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年06月17日 ***@***.***> 写道： 




大佬,你好,预测的时候出错,即用step3时,出现错误(用的给的样例文本)





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Veyronl** [comment]
好的,感谢大佬的及时回复和处理
